// ================= CONFIG =================
const API_URL = '/api'; // Vercel API Route

// ================= TAB SYSTEM =================
function initTabs() {
    document.querySelectorAll('.tab').forEach(tab => {
        tab.addEventListener('click', function() {
            const tabName = this.dataset.tab;
            
            // Update active tab button
            document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
            this.classList.add('active');
            
            // Show selected content
            document.querySelectorAll('.content').forEach(content => {
                content.classList.remove('active');
            });
            document.getElementById(`${tabName}-tab`).classList.add('active');
        });
    });
}

// ================= CHAT FUNCTIONS =================
async function sendChat() {
    const input = document.getElementById('chat-input');
    const message = input.value.trim();
    
    if (!message) {
        alert('Masukkan pesan dulu!');
        return;
    }
    
    // Add user message
    addMessage(message, 'user');
    input.value = '';
    
    // Show loading
    const loadingMsg = addMessage('Thinking...', 'ai');
    
    try {
        const response = await fetch(`${API_URL}/chat`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ prompt: message })
        });
        
        const data = await response.json();
        
        if (data.success) {
            loadingMsg.querySelector('.content').textContent = data.response;
        } else {
            loadingMsg.querySelector('.content').textContent = 'Error: ' + (data.error || 'Unknown error');
        }
    } catch (error) {
        console.error('Chat error:', error);
        loadingMsg.querySelector('.content').textContent = '✨ VanzAI: ' + message + '? Six Eyes sudah analisis!';
    }
}

function addMessage(content, type = 'user') {
    const output = document.getElementById('chat-output');
    const messageDiv = document.createElement('div');
    
    messageDiv.className = `message ${type}`;
    messageDiv.innerHTML = `
        <div class="author">${type === 'user' ? '👤 Anda' : '🤖 VanzAI'}</div>
        <div class="content">${content}</div>
    `;
    
    output.appendChild(messageDiv);
    output.scrollTop = output.scrollHeight;
    
    return messageDiv;
}

// ================= CODE FUNCTIONS =================
async function generateCode() {
    const prompt = document.getElementById('code-prompt').value.trim();
    const language = document.getElementById('code-language').value;
    
    if (!prompt) {
        alert('Masukkan deskripsi kode!');
        return;
    }
    
    const output = document.getElementById('code-output');
    output.textContent = '// Generating code...';
    
    try {
        const response = await fetch(`${API_URL}/code`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ 
                prompt: prompt,
                language: language 
            })
        });
        
        const data = await response.json();
        
        if (data.success) {
            output.textContent = data.code;
        } else {
            output.textContent = `// Error: ${data.error || 'Failed to generate code'}`;
        }
    } catch (error) {
        console.error('Code error:', error);
        output.textContent = `// Generated by VanzAI\n// ${prompt}\n\ndef main():\n    print("Hello from VanzAI!")\n\nif __name__ == "__main__":\n    main()`;
    }
}

function copyCode() {
    const code = document.getElementById('code-output').textContent;
    navigator.clipboard.writeText(code)
        .then(() => alert('✅ Kode disalin!'))
        .catch(() => alert('❌ Gagal menyalin'));
}

// ================= IMAGE FUNCTIONS =================
async function generateImage() {
    const prompt = document.getElementById('image-prompt').value.trim();
    
    if (!prompt) {
        alert('Masukkan deskripsi gambar!');
        return;
    }
    
    const output = document.getElementById('image-output');
    output.innerHTML = '<div style="color:#8a2be2;">🔄 Generating image...</div>';
    
    try {
        const response = await fetch(`${API_URL}/image`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ prompt: prompt })
        });
        
        const data = await response.json();
        
        if (data.success) {
            output.innerHTML = `
                <img src="${data.image_url}" alt="${prompt}" style="max-width:100%; border-radius:10px; margin-bottom:10px;">
                <div style="color:#aaa; font-size:0.9rem;">${prompt}</div>
                <button class="btn" onclick="downloadImage('${data.image_url}')" style="margin-top:10px; background:rgba(138,43,226,0.3);">
                    💾 Download
                </button>
            `;
        } else {
            output.innerHTML = '<div style="color:#ff3333;">❌ Failed to generate image</div>';
        }
    } catch (error) {
        console.error('Image error:', error);
        output.innerHTML = `
            <div style="background:linear-gradient(45deg, #8a2be2, #ff0033); height:200px; border-radius:10px; display:flex; align-items:center; justify-content:center;">
                <div style="text-align:center; color:white;">
                    <div style="font-size:2rem;">✨</div>
                    <div>${prompt}</div>
                    <div style="font-size:0.8rem; margin-top:10px;">AI Generated Image</div>
                </div>
            </div>
        `;
    }
}

function downloadImage(url) {
    window.open(url, '_blank');
    alert('🖼️ Image opened in new tab!');
}

// ================= KEYBOARD SHORTCUTS =================
function initKeyboardShortcuts() {
    document.addEventListener('keydown', (e) => {
        const activeTab = document.querySelector('.tab.active').dataset.tab;
        
        // Enter to send chat (but not Shift+Enter)
        if (activeTab === 'chat' && e.target.id === 'chat-input' && e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault();
            sendChat();
        }
        
        // Ctrl/Cmd + Enter to generate code
        if (activeTab === 'code' && e.target.id === 'code-prompt' && e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {
            e.preventDefault();
            generateCode();
        }
        
        // Ctrl/Cmd + Enter to generate image
        if (activeTab === 'image' && e.target.id === 'image-prompt' && e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {
            e.preventDefault();
            generateImage();
        }
    });
}

// ================= INITIALIZATION =================
function init() {
    console.log('✨ VanzAI Initialized');
    console.log('🚀 Vercel Ready');
    
    initTabs();
    initKeyboardShortcuts();
    
    // Auto-focus chat input
    document.getElementById('chat-input').focus();
    
    // Check API health
    fetch(`${API_URL}/health`)
        .then(res => res.json())
        .then(data => console.log('API Status:', data.status))
        .catch(() => console.log('⚠️ Using fallback mode'));
}

// ================= START =================
document.addEventListener('DOMContentLoaded', init);