// Vercel Serverless Function - /api/index.js

module.exports = (req, res) => {
  // Set CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  
  // Handle preflight
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }
  
  // Parse JSON body
  let body = {};
  if (req.method === 'POST') {
    try {
      body = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
    } catch (e) {
      body = {};
    }
  }
  
  const { prompt, language } = body;
  
  // API Routes
  if (req.method === 'POST') {
    // CHAT API
    if (req.url === '/api/chat' || req.url === '/chat') {
      const responses = [
        `✨ VanzAI: "${prompt || 'Hello'}"? Six Eyes sudah analisis!`,
        `🔥 ${prompt || 'That'}? Limitless mode handle itu dengan mudah!`,
        `💀 Yare yare... ${prompt || 'request'} sudah selesai.`,
        `⚡ Domain Expansion activated untuk: ${prompt || 'this request'}`,
        `🤖 ${prompt || 'Hello'}? Saya VanzAI, AI terkuat! Sudah selesai.`
      ];
      
      return res.status(200).json({
        success: true,
        response: responses[Math.floor(Math.random() * responses.length)],
        model: 'VanzAI-SixEyes'
      });
    }
    
    // IMAGE API
    if (req.url === '/api/image' || req.url === '/image') {
      const imageText = (prompt || 'AI Art').substring(0, 30).replace(/[^a-zA-Z0-9]/g, '+');
      return res.status(200).json({
        success: true,
        image_url: `https://placehold.co/600x400/8a2be2/white?text=${imageText}`,
        prompt: prompt || 'AI Art'
      });
    }
    
    // CODE API
    if (req.url === '/api/code' || req.url === '/code') {
      const templates = {
        python: `# Generated by VanzAI - Six Eyes Technology
# Prompt: ${prompt || 'Hello World'}

def main():
    """Main function generated by VanzAI"""
    print("✨ VanzAI Activated!")
    # Your code logic here
    return "Success"

if __name__ == "__main__":
    result = main()
    print(f"Result: {result}")`,
        
        javascript: `// Generated by VanzAI - Six Eyes Technology
// Prompt: ${prompt || 'Hello World'}

function vanzAI() {
    console.log("✨ VanzAI Activated!");
    // Your code here
    return "Success";
}

// Execute
const result = vanzAI();
console.log(\`Result: \${result}\`);`,
        
        html: `<!DOCTYPE html>
<!-- Generated by VanzAI - Six Eyes Technology -->
<!-- Prompt: ${prompt || 'Hello World'} -->
<html>
<head>
    <title>VanzAI Generated</title>
    <style>
        body { 
            background: #0a0a2a;
            color: white;
            font-family: Arial;
            padding: 20px;
        }
        .title { color: #8a2be2; }
    </style>
</head>
<body>
    <h1 class="title">✨ VanzAI Generated Page</h1>
    <p>${prompt || 'Hello World'}</p>
</body>
</html>`
      };
      
      return res.status(200).json({
        success: true,
        code: templates[language] || templates.python,
        language: language || 'python'
      });
    }
  }
  
  // HEALTH CHECK
  if (req.method === 'GET' && (req.url === '/api/health' || req.url === '/health')) {
    return res.status(200).json({
      status: 'online',
      service: 'VanzAI API',
      version: '1.0.0',
      timestamp: new Date().toISOString()
    });
  }
  
  // 404 for unknown routes
  return res.status(404).json({ 
    success: false, 
    error: 'Route not found',
    path: req.url,
    method: req.method 
  });
};
